baseURL = 'http://blockbite.ch/'
languageCode = 'en-us'
title = 'BlockBite'
theme = 'blockbite'
languagecode = "en"
defaultcontentlanguage = "en"

disqusShortname = "yourdiscussshortname"

[services]
  [services.googleAnalytics]
    ID = 'G-E865EQNC89'

[markup.highlight]
style = "github-dark"

[params]
  author = "Mathias Scherer"
  info = "Solidity Dev, DevOps Engineer, Security Nerd"
  description = "BlockBite - Experienced freelancer in Solidity, Typescript, DevOps, and security, offering tailored solutions for blockchain and backend projects, and open to unique challenges beyond, with easy contact via email and social media."
  keywords = "EVM, Freelance Solidity Developer, Typescript Development Services, Blockchain Smart Contracts, Security Audits for Blockchain, DevOps Engineer, Ethereum Blockchain Development, Backend Development Solutions, Custom Software Development, IT Freelancer, Web Application Security, Freelance IT Consultant, Solidity Smart Contracts, Typescript Backend Development, Blockchain Project Consulting, Cybersecurity Expertise, IT Solutions Provider, Freelance DevOps Specialist, Ethereum DApp Development, Code Quality Assurance"
  avatarurl = "images/white_text_transparent.png"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/images/white.svg"

  since = 2023

  logo = "images/black_text_wide.svg"
  punchLines = ["You Ask, I Build", "Code That Works", "Fast. Clean. Done.", "No BS. Just Code."]

  customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

# Social links
[[params.social]]
  name = "Github"
  vendor = "font-awesome-brands"
  icon = "github"
  weight = 1
  url = "https://github.com/mathewmeconry/"
  text = "mathewmeconry"
[[params.social]]
  name = "Telegram"
  vendor = "font-awesome-brands"
  icon = "telegram"
  weight = 2
  url = "https://t.me/mathewmeconry/"
  text = "@mathewmeconry"
[[params.social]]
  name = "Twitter"
  vendor = "font-awesome-brands"
  icon = "twitter"
  weight = 3
  url = "https://twitter.com/mathewmeconry/"
  text = "@mathewmeconry"
[[params.social]]
  name = "LinkedIn"
  vendor = "font-awesome-brands"
  icon = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/mathias-scherer-4a15b5114/"
  text = "Mathias Scherer"
[[params.social]]
  name = "E-Mail"
  vendor = "font-awesome-solid"
  icon = "envelope"
  weight = 3
  url = "mailto:mathias@blockbite.ch"
  text = "mathias@blockbite.ch"

# Menu links
[[menus.main]]
  name = "Services"
  weight = 1
  url = "/services/"
[[menus.main]]
  name = "Customers"
  weight = 2
  url = "/customers/"
[[menus.main]]
  name = "About"
  weight = 3
  url = "/about/"
[[menus.main]]
  name = "Get In Touch"
  weight = 4
  url = "/contact/"

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'
  [[module.imports]]
    path = 'github.com/hugomods/icons/vendors/lucide'
  [[module.imports]]
    path = 'github.com/hugomods/icons/vendors/font-awesome'
  [[module.imports]]
    path = 'github.com/hugomods/google-analytics'